### ISSUE TITLE
지도표시를 못하고있습니다. 

### ISSUE THREAD

**Issue by hangum** [Gaia3D/SpatialDataManager#28]
화면은 다음과 같습니다.
<img width="1029" alt="2015-12-08 6 21 40" src="https://cloud.githubusercontent.com/assets/1335915/11652049/a4c6b9be-9dd8-11e5-9015-ec5deeafcc86.png">

자바스크립트 오류가 다음과 같이 나고있습니다.
GET https://a.tiles.mapbox.com/v3/examples.map-20v6611k/3/7/2.png 
GET https://b.tiles.mapbox.com/v3/examples.map-20v6611k/3/7/3.png

**Comment by jangbi882** [comment]
기존에 쓰던 배경지도의 url이 수정되어 발생한 문제입니다.
새로운 url로 바꾸어 해결했습니다.
